config/routes.rb
Rails.application.routes.draw do

	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

	# Defines the root path route ("/")
	root 'dashboards#index'

	namespace :ceefax do
		resources :appearances
		resources :assists
		namespace :player_seasons do
			resources :attacking_stats
			resources :defensive_stats
			resources :discipline_stats
		end
		namespace :team_seasons do
			resources :goals_conceded_stats
			resources :goals_scored_stats
			resources :red_cards_stats
			resources :yellow_cards_stats
		end
		resources :cards
		resources :corners
		resources :countries
		resources :dashboards
		resources :fixtures
		resources :goals
		resources :head_to_heads
		resources :leagues
		resources :players
		resources :player_seasons
		resources :object_handling_failures
		resources :referees
		resources :referee_fixtures
		resources :seasons
		resources :season_game_weeks
		resources :teams
		resources :team_seasons

		root to: "dashboards#index"
	end

	resources :dashboards

	resources :countries do
		resources :leagues, only: [:index, :show, :update, :destroy] do
			resources :teams do
				resources :players, only: [:show, :update, :destroy]
			end
			resources :seasons, only: [:show, :update, :destroy] do
				member do
					get 'scorers_streaming'
					get 'assists_streaming'
					get 'bookings_streaming'
					get 'reds_streaming'
				end

				resources :teams, only: [:show] do
					resources :players, only: [:show, :update, :destroy]
				end

				resources :player_seasons
				resources :fixtures
				resources :assists
				resources :cards
				resources :goals
				resources :referees, only: [:index, :show, :update, :destroy]
			end
		end
	end

	resources :discipline_stats
	resources :defensive_stats
	resources :attacking_stats
	resources :corners
	resources :head_to_heads
	resources :fixtures, only: [:index]
	resources :referee_fixtures
	resources :referees
	resources :goals_conceded_stats
	resources :goals_scored_stats
	resources :leagues, only: [:index]
	resources :players, only: [:index, :show] do
		collection do
			get 'players_streaming'
		end
	end
	resources :team_seasons
	resources :teams, only: [:index, :show, :update, :destroy]

	get 'team_player_season_goals/:team_season_id', to: 'charts#team_player_season_goals', as: 'team_player_season_goals'
	get 'team_player_season_assists/:team_season_id', to: 'charts#team_player_season_assists', as: 'team_player_season_assists'
	get 'team_player_season_yellow_cards/:team_season_id', to: 'charts#team_player_season_yellow_cards', as: 'team_player_season_yellow_cards'
	get 'team_goals_radar/:current_team_season_id/:opponent_team_season_id', to: 'charts#team_goals_radar', as: 'team_goals_radar'
	get 'team_cards_line_chart/:current_team_season_id/:opponent_team_season_id', to: 'charts#team_cards_line_chart', as: 'team_cards_line_chart'
	get '/search', to: 'dashboards#search', as: 'search'

end

app/models/player_seasons/discipline_stat.rb
# == Schema Information
#
# Table name: discipline_stats
#
#  id                           :bigint           not null, primary key
#  red_card_away                :integer          default(0)
#  red_card_away_first_half     :integer          default(0)
#  red_card_away_second_half    :integer          default(0)
#  red_card_first_half          :integer          default(0)
#  red_card_home                :integer          default(0)
#  red_card_home_first_half     :integer          default(0)
#  red_card_home_second_half    :integer          default(0)
#  red_card_second_half         :integer          default(0)
#  red_card_total               :integer          default(0)
#  yellow_card_away             :integer          default(0)
#  yellow_card_away_first_half  :integer          default(0)
#  yellow_card_away_second_half :integer          default(0)
#  yellow_card_first_half       :integer          default(0)
#  yellow_card_home             :integer          default(0)
#  yellow_card_home_first_half  :integer          default(0)
#  yellow_card_home_second_half :integer          default(0)
#  yellow_card_second_half      :integer          default(0)
#  yellow_card_total            :integer          default(0)
#  player_season_id             :bigint           not null
#
# Indexes
#
#  index_discipline_stats_on_player_season_id  (player_season_id)
#
# Foreign Keys
#
#  fk_rails_...  (player_season_id => player_seasons.id)
#
module PlayerSeasons
	class DisciplineStat < ApplicationRecord
		self.table_name = 'discipline_stats'

		belongs_to :player_season
	end
end

app/controllers/ceefax/player_seasons/discipline_stats_controller.rb
module Ceefax
	class PlayerSeasons::DisciplineStatsController < Ceefax::ApplicationController
		# Overwrite any of the RESTful controller actions to implement custom behavior
		# For example, you may want to send an email after a foo is updated.
		#
		# def update
		#   super
		#   send_foo_updated_email(requested_resource)
		# end

		# Override this method to specify custom lookup behavior.
		# This will be used to set the resource for the `show`, `edit`, and `update`
		# actions.
		#
		# def find_resource(param)
		#   Foo.find_by!(slug: param)
		# end

		# The result of this lookup will be available as `requested_resource`

		# Override this if you have certain roles that require a subset
		# this will be used to set the records shown on the `index` action.
		#
		# def scoped_resource
		#   if current_user.super_admin?
		#     resource_class
		#   else
		#     resource_class.with_less_stuff
		#   end
		# end

		# Override `resource_params` if you want to transform the submitted
		# data before it's persisted. For example, the following would turn all
		# empty values into nil values. It uses other APIs such as `resource_class`
		# and `dashboard`:
		#
		# def resource_params
		#   params.require(resource_class.model_name.param_key).
		#     permit(dashboard.permitted_attributes(action_name)).
		#     transform_values { |value| value == "" ? nil : value }
		# end

		# See https://administrate-demo.herokuapp.com/customizing_controller_actions
		# for more information
	end
end

app/controllers/discipline_stats_controller.rb
class DisciplineStatsController < ApplicationController
  before_action :set_discipline_stat, only: %i[ show edit update destroy ]

  # GET /discipline_stats or /discipline_stats.json
  def index
    @discipline_stats = DisciplineStat.all
  end

  # GET /discipline_stats/1 or /discipline_stats/1.json
  def show
  end

  # GET /discipline_stats/new
  def new
    @discipline_stat = DisciplineStat.new
  end

  # GET /discipline_stats/1/edit
  def edit
  end

  # POST /discipline_stats or /discipline_stats.json
  def create
    @discipline_stat = DisciplineStat.new(discipline_stat_params)

    respond_to do |format|
      if @discipline_stat.save
        format.html { redirect_to discipline_stat_url(@discipline_stat), notice: "Discipline stat was successfully created." }
        format.json { render :show, status: :created, location: @discipline_stat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @discipline_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discipline_stats/1 or /discipline_stats/1.json
  def update
    respond_to do |format|
      if @discipline_stat.update(discipline_stat_params)
        format.html { redirect_to discipline_stat_url(@discipline_stat), notice: "Discipline stat was successfully updated." }
        format.json { render :show, status: :ok, location: @discipline_stat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @discipline_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discipline_stats/1 or /discipline_stats/1.json
  def destroy
    @discipline_stat.destroy

    respond_to do |format|
      format.html { redirect_to discipline_stats_url, notice: "Discipline stat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discipline_stat
      @discipline_stat = DisciplineStat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def discipline_stat_params
      params.fetch(:discipline_stat, {})
    end
end

app/helpers/discipline_stats_helper.rb
module DisciplineStatsHelper
end

app/views/discipline_stats/_discipline_stat.html.erb
<div id="<%= dom_id discipline_stat %>">
  <% if action_name != "show" %>
    <%= link_to "Show this discipline stat", discipline_stat, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this discipline stat', edit_discipline_stat_path(discipline_stat), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/discipline_stats/_form.html.erb
<%= form_with(model: discipline_stat, class: "contents") do |form| %>
  <% if discipline_stat.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(discipline_stat.errors.count, "error") %> prohibited this discipline_stat from being saved:</h2>

      <ul>
        <% discipline_stat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/discipline_stats/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing discipline stat</h1>

  <%= render "form", discipline_stat: @discipline_stat %>

  <%= link_to "Show this discipline stat", @discipline_stat, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to discipline stats", discipline_stats_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/discipline_stats/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Discipline stats</h1>
    <%= link_to 'New discipline stat', new_discipline_stat_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="discipline_stats" class="min-w-full">
    <%= render @discipline_stats %>
  </div>
</div>

app/views/discipline_stats/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New discipline stat</h1>

  <%= render "form", discipline_stat: @discipline_stat %>

  <%= link_to 'Back to discipline stats', discipline_stats_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/discipline_stats/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @discipline_stat %>

    <%= link_to 'Edit this discipline_stat', edit_discipline_stat_path(@discipline_stat), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this discipline_stat', discipline_stat_path(@discipline_stat), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to discipline_stats', discipline_stats_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>