config/routes.rb
Rails.application.routes.draw do

	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

	# Defines the root path route ("/")
	root 'dashboards#index'

	namespace :ceefax do
		resources :appearances
		resources :assists
		namespace :player_seasons do
			resources :attacking_stats
			resources :defensive_stats
			resources :discipline_stats
		end
		namespace :team_seasons do
			resources :goals_conceded_stats
			resources :goals_scored_stats
			resources :red_cards_stats
			resources :yellow_cards_stats
		end
		resources :cards
		resources :corners
		resources :countries
		resources :dashboards
		resources :fixtures
		resources :goals
		resources :head_to_heads
		resources :leagues
		resources :players
		resources :player_seasons
		resources :object_handling_failures
		resources :referees
		resources :referee_fixtures
		resources :seasons
		resources :season_game_weeks
		resources :teams
		resources :team_seasons

		root to: "dashboards#index"
	end

	resources :dashboards

	resources :countries do
		resources :leagues, only: [:index, :show, :update, :destroy] do
			resources :teams do
				resources :players, only: [:show, :update, :destroy]
			end
			resources :seasons, only: [:show, :update, :destroy] do
				member do
					get 'scorers_streaming'
					get 'assists_streaming'
					get 'bookings_streaming'
					get 'reds_streaming'
				end

				resources :teams, only: [:show] do
					resources :players, only: [:show, :update, :destroy]
				end

				resources :player_seasons
				resources :fixtures
				resources :assists
				resources :cards
				resources :goals
				resources :referees, only: [:index, :show, :update, :destroy]
			end
		end
	end

	resources :discipline_stats
	resources :defensive_stats
	resources :attacking_stats
	resources :corners
	resources :head_to_heads
	resources :fixtures, only: [:index]
	resources :referee_fixtures
	resources :referees
	resources :goals_conceded_stats
	resources :goals_scored_stats
	resources :leagues, only: [:index]
	resources :players, only: [:index, :show] do
		collection do
			get 'players_streaming'
		end
	end
	resources :team_seasons
	resources :teams, only: [:index, :show, :update, :destroy]

	get 'team_player_season_goals/:team_season_id', to: 'charts#team_player_season_goals', as: 'team_player_season_goals'
	get 'team_player_season_assists/:team_season_id', to: 'charts#team_player_season_assists', as: 'team_player_season_assists'
	get 'team_player_season_yellow_cards/:team_season_id', to: 'charts#team_player_season_yellow_cards', as: 'team_player_season_yellow_cards'
	get 'team_goals_radar/:current_team_season_id/:opponent_team_season_id', to: 'charts#team_goals_radar', as: 'team_goals_radar'
	get 'team_cards_line_chart/:current_team_season_id/:opponent_team_season_id', to: 'charts#team_cards_line_chart', as: 'team_cards_line_chart'
	get '/search', to: 'dashboards#search', as: 'search'

end

app/models/goals_scored_stat.rb
# == Schema Information
#
# Table name: goals_scored_stats
#
#  id               :bigint           not null, primary key
#  away             :integer          default(0)
#  away_first_half  :integer          default(0)
#  away_second_half :integer          default(0)
#  first_half       :integer          default(0)
#  home             :integer          default(0)
#  home_first_half  :integer          default(0)
#  home_second_half :integer          default(0)
#  second_half      :integer          default(0)
#  total            :integer          default(0)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  team_season_id   :bigint           not null
#
# Indexes
#
#  index_goals_scored_stats_on_team_season_id  (team_season_id)
#
# Foreign Keys
#
#  fk_rails_...  (team_season_id => team_seasons.id)
#
class GoalsScoredStat < ApplicationRecord
	belongs_to :team_season
end

app/models/team_seasons/goals_scored_stat.rb
# == Schema Information
#
# Table name: goals_scored_stats
#
#  id               :bigint           not null, primary key
#  away             :integer          default(0)
#  away_first_half  :integer          default(0)
#  away_second_half :integer          default(0)
#  first_half       :integer          default(0)
#  home             :integer          default(0)
#  home_first_half  :integer          default(0)
#  home_second_half :integer          default(0)
#  second_half      :integer          default(0)
#  total            :integer          default(0)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  team_season_id   :bigint           not null
#
# Indexes
#
#  index_goals_scored_stats_on_team_season_id  (team_season_id)
#
# Foreign Keys
#
#  fk_rails_...  (team_season_id => team_seasons.id) ON DELETE => cascade
#

module TeamSeasons
	class GoalsScoredStat < ApplicationRecord
		self.table_name = 'goals_scored_stats'

		belongs_to :team_season
	end
end

app/controllers/ceefax/goals_scored_stats_controller.rb
module Admin
  class GoalsScoredStatsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/ceefax/team_seasons/goals_scored_stats_controller.rb
module Ceefax
	class TeamSeasons::GoalsScoredStatsController < Ceefax::ApplicationController
		# Overwrite any of the RESTful controller actions to implement custom behavior
		# For example, you may want to send an email after a foo is updated.
		#
		# def update
		#   super
		#   send_foo_updated_email(requested_resource)
		# end

		# Override this method to specify custom lookup behavior.
		# This will be used to set the resource for the `show`, `edit`, and `update`
		# actions.
		#
		# def find_resource(param)
		#   Foo.find_by!(slug: param)
		# end

		# The result of this lookup will be available as `requested_resource`

		# Override this if you have certain roles that require a subset
		# this will be used to set the records shown on the `index` action.
		#
		# def scoped_resource
		#   if current_user.super_admin?
		#     resource_class
		#   else
		#     resource_class.with_less_stuff
		#   end
		# end

		# Override `resource_params` if you want to transform the submitted
		# data before it's persisted. For example, the following would turn all
		# empty values into nil values. It uses other APIs such as `resource_class`
		# and `dashboard`:
		#
		# def resource_params
		#   params.require(resource_class.model_name.param_key).
		#     permit(dashboard.permitted_attributes(action_name)).
		#     transform_values { |value| value == "" ? nil : value }
		# end

		# See https://administrate-demo.herokuapp.com/customizing_controller_actions
		# for more information
	end
end

app/controllers/goals_scored_stats_controller.rb
class GoalsScoredStatsController < ApplicationController
  before_action :set_goals_scored_stat, only: %i[ show edit update destroy ]

  # GET /goals_scored_stats or /goals_scored_stats.json
  def index
    @goals_scored_stats = GoalsScoredStat.all
  end

  # GET /goals_scored_stats/1 or /goals_scored_stats/1.json
  def show
  end

  # GET /goals_scored_stats/new
  def new
    @goals_scored_stat = GoalsScoredStat.new
  end

  # GET /goals_scored_stats/1/edit
  def edit
  end

  # POST /goals_scored_stats or /goals_scored_stats.json
  def create
    @goals_scored_stat = GoalsScoredStat.new(goals_scored_stat_params)

    respond_to do |format|
      if @goals_scored_stat.save
        format.html { redirect_to goals_scored_stat_url(@goals_scored_stat), notice: "Goals scored stat was successfully created." }
        format.json { render :show, status: :created, location: @goals_scored_stat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @goals_scored_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals_scored_stats/1 or /goals_scored_stats/1.json
  def update
    respond_to do |format|
      if @goals_scored_stat.update(goals_scored_stat_params)
        format.html { redirect_to goals_scored_stat_url(@goals_scored_stat), notice: "Goals scored stat was successfully updated." }
        format.json { render :show, status: :ok, location: @goals_scored_stat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @goals_scored_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals_scored_stats/1 or /goals_scored_stats/1.json
  def destroy
    @goals_scored_stat.destroy

    respond_to do |format|
      format.html { redirect_to goals_scored_stats_url, notice: "Goals scored stat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goals_scored_stat
      @goals_scored_stat = GoalsScoredStat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def goals_scored_stat_params
      params.fetch(:goals_scored_stat, {})
    end
end

app/helpers/goals_scored_stats_helper.rb
module GoalsScoredStatsHelper
end

app/views/goals_scored_stats/_form.html.erb
<%= form_with(model: goals_scored_stat, class: "contents") do |form| %>
  <% if goals_scored_stat.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(goals_scored_stat.errors.count, "error") %> prohibited this goals_scored_stat from being saved:</h2>

      <ul>
        <% goals_scored_stat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/goals_scored_stats/_goals_scored_stat.html.erb
<div id="<%= dom_id goals_scored_stat %>">
  <% if action_name != "show" %>
    <%= link_to "Show this goals scored stat", goals_scored_stat, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this goals scored stat', edit_goals_scored_stat_path(goals_scored_stat), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/goals_scored_stats/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing goals scored stat</h1>

  <%= render "form", goals_scored_stat: @goals_scored_stat %>

  <%= link_to "Show this goals scored stat", @goals_scored_stat, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to goals scored stats", goals_scored_stats_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/goals_scored_stats/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Goals scored stats</h1>
    <%= link_to 'New goals scored stat', new_goals_scored_stat_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="goals_scored_stats" class="min-w-full">
    <%= render @goals_scored_stats %>
  </div>
</div>

app/views/goals_scored_stats/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New goals scored stat</h1>

  <%= render "form", goals_scored_stat: @goals_scored_stat %>

  <%= link_to 'Back to goals scored stats', goals_scored_stats_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/goals_scored_stats/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @goals_scored_stat %>

    <%= link_to 'Edit this goals_scored_stat', edit_goals_scored_stat_path(@goals_scored_stat), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this goals_scored_stat', goals_scored_stat_path(@goals_scored_stat), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to goals_scored_stats', goals_scored_stats_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>