config/routes.rb
Rails.application.routes.draw do

	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

	# Defines the root path route ("/")
	root 'dashboards#index'

	namespace :ceefax do
		resources :appearances
		resources :assists
		namespace :player_seasons do
			resources :attacking_stats
			resources :defensive_stats
			resources :discipline_stats
		end
		namespace :team_seasons do
			resources :goals_conceded_stats
			resources :goals_scored_stats
			resources :red_cards_stats
			resources :yellow_cards_stats
		end
		resources :cards
		resources :corners
		resources :countries
		resources :dashboards
		resources :fixtures
		resources :goals
		resources :head_to_heads
		resources :leagues
		resources :players
		resources :player_seasons
		resources :object_handling_failures
		resources :referees
		resources :referee_fixtures
		resources :seasons
		resources :season_game_weeks
		resources :teams
		resources :team_seasons

		root to: "dashboards#index"
	end

	resources :dashboards

	resources :countries do
		resources :leagues, only: [:index, :show, :update, :destroy] do
			resources :teams do
				resources :players, only: [:show, :update, :destroy]
			end
			resources :seasons, only: [:show, :update, :destroy] do
				member do
					get 'scorers_streaming'
					get 'assists_streaming'
					get 'bookings_streaming'
					get 'reds_streaming'
				end

				resources :teams, only: [:show] do
					resources :players, only: [:show, :update, :destroy]
				end

				resources :player_seasons
				resources :fixtures
				resources :assists
				resources :cards
				resources :goals
				resources :referees, only: [:index, :show, :update, :destroy]
			end
		end
	end

	resources :discipline_stats
	resources :defensive_stats
	resources :attacking_stats
	resources :corners
	resources :head_to_heads
	resources :fixtures, only: [:index]
	resources :referee_fixtures
	resources :referees
	resources :goals_conceded_stats
	resources :goals_scored_stats
	resources :leagues, only: [:index]
	resources :players, only: [:index, :show] do
		collection do
			get 'players_streaming'
		end
	end
	resources :team_seasons
	resources :teams, only: [:index, :show, :update, :destroy]

	get 'team_player_season_goals/:team_season_id', to: 'charts#team_player_season_goals', as: 'team_player_season_goals'
	get 'team_player_season_assists/:team_season_id', to: 'charts#team_player_season_assists', as: 'team_player_season_assists'
	get 'team_player_season_yellow_cards/:team_season_id', to: 'charts#team_player_season_yellow_cards', as: 'team_player_season_yellow_cards'
	get 'team_goals_radar/:current_team_season_id/:opponent_team_season_id', to: 'charts#team_goals_radar', as: 'team_goals_radar'
	get 'team_cards_line_chart/:current_team_season_id/:opponent_team_season_id', to: 'charts#team_cards_line_chart', as: 'team_cards_line_chart'
	get '/search', to: 'dashboards#search', as: 'search'

end

app/models/assist.rb
# == Schema Information
#
# Table name: assists
#
#  id               :bigint           not null, primary key
#  is_home          :boolean
#  minute           :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  appearance_id    :bigint           not null
#  fixture_id       :bigint           not null
#  goal_id          :bigint           not null
#  player_season_id :bigint           not null
#  team_season_id   :bigint           not null
#
# Indexes
#
#  index_assists_on_appearance_id     (appearance_id)
#  index_assists_on_fixture_id        (fixture_id)
#  index_assists_on_goal_id           (goal_id)
#  index_assists_on_player_season_id  (player_season_id)
#  index_assists_on_team_season_id    (team_season_id)
#
# Foreign Keys
#
#  fk_rails_...  (appearance_id => appearances.id) ON DELETE => cascade
#  fk_rails_...  (fixture_id => fixtures.id) ON DELETE => cascade
#  fk_rails_...  (goal_id => goals.id) ON DELETE => cascade
#  fk_rails_...  (player_season_id => player_seasons.id) ON DELETE => cascade
#  fk_rails_...  (team_season_id => team_seasons.id) ON DELETE => cascade
#
class Assist < ApplicationRecord
	belongs_to :player_season, counter_cache: true
	belongs_to :goal
	belongs_to :team_season, counter_cache: true
	belongs_to :fixture
	belongs_to :appearance, counter_cache: true

	scope :by_season, -> (season_id) {
		joins(team_season: :season)
			.where('seasons.id = ?', season_id)
			.includes(:player_season, :team_season)
			.group(:player_season_id)
			.order('COUNT(assists.id) desc')
			.count('assists.id')
	}

	def player_name
		player_season.return_name
	end
end

app/models/calculators/player_season/assists.rb
module Calculators
	module PlayerSeason
		class Assists
			def initialize(player_season)
				@player_season = player_season
			end

			def season_assists_size
				player_season.assists.size
			end

			def home_assists_count
				home_assists.count
			end

			def away_assists_count
				away_assists.count
			end

			def first_half_assists_count
				first_half_assists.count
			end

			def second_half_assists_count
				second_half_assists.count
			end

			def first_half_home_assists_count
				first_half_assists.where(is_home: true).count
			end

			def first_half_away_assists_count
				first_half_assists.where(is_home: nil).count
			end

			def second_half_home_assists_count
				second_half_assists.where(is_home: true).count
			end

			def second_half_away_assists_count
				second_half_assists.where(is_home: nil).count
			end

			def average_minutes_per_assist
				return ::PlayerSeason::ZERO if season_assists_size.zero?

				player_season.total_minutes_played / season_assists_size
			end

			def average_minutes_per_home_assist
				return ::PlayerSeason::ZERO if home_assists_count.zero?

				player_season.total_home_minutes_played / home_assists_count
			end

			def average_minutes_per_away_assist
				return ::PlayerSeason::ZERO if away_assists_count.zero?

				player_season.total_away_minutes_played / away_assists_count
			end

			private

			attr_reader :player_season

			def home_assists
				player_season.assists.where(is_home: true)
			end

			def away_assists
				player_season.assists.where(is_home: nil)
			end

			def first_half_assists
				player_season.assists.where(minute: 0..45)
			end

			def second_half_assists
				player_season.assists.where(minute: 46..100)
			end
		end
	end
end

app/controllers/admin/assists_controller.rb
module Admin
  class AssistsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/assists_controller.rb
class AssistsController < ApplicationController
  before_action :set_assist, only: %i[ show edit update destroy ]

  # GET /assists or /assists.json
  def index
    @assists = Assist.all
  end

  # GET /assists/1 or /assists/1.json
  def show
  end

  # GET /assists/new
  def new
    @assist = Assist.new
  end

  # GET /assists/1/edit
  def edit
  end

  # POST /assists or /assists.json
  def create
    @assist = Assist.new(assist_params)

    respond_to do |format|
      if @assist.save
        format.html { redirect_to assist_url(@assist), notice: "Assist was successfully created." }
        format.json { render :show, status: :created, location: @assist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @assist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assists/1 or /assists/1.json
  def update
    respond_to do |format|
      if @assist.update(assist_params)
        format.html { redirect_to assist_url(@assist), notice: "Assist was successfully updated." }
        format.json { render :show, status: :ok, location: @assist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @assist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assists/1 or /assists/1.json
  def destroy
    @assist.destroy

    respond_to do |format|
      format.html { redirect_to assists_url, notice: "Assist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assist
      @assist = Assist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def assist_params
      params.require(:assist).permit(:player_season_id, :goal_id, :team_season_id, :fixture_id, :appearances_id, :is_home, :minute)
    end
end

app/controllers/ceefax/assists_controller.rb
module Ceefax
  class AssistsController < Ceefax::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/helpers/assists_helper.rb
module AssistsHelper
end

app/views/assists/_assist.html.erb
<div id="<%= dom_id assist %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Player season:</strong>
    <%= assist.player_season_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Goal:</strong>
    <%= assist.goal_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Team season:</strong>
    <%= assist.team_season_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Fixture:</strong>
    <%= assist.fixture_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Appearances:</strong>
    <%= assist.appearances_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Is home:</strong>
    <%= assist.is_home %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Minute:</strong>
    <%= assist.minute %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this assist", assist, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this assist', edit_assist_path(assist), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/assists/_form.html.erb
<%= form_with(model: assist, class: "contents") do |form| %>
  <% if assist.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(assist.errors.count, "error") %> prohibited this assist from being saved:</h2>

      <ul>
        <% assist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :player_season_id %>
    <%= form.text_field :player_season_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :goal_id %>
    <%= form.text_field :goal_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :team_season_id %>
    <%= form.text_field :team_season_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :fixture_id %>
    <%= form.text_field :fixture_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :appearances_id %>
    <%= form.text_field :appearances_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :is_home %>
    <%= form.check_box :is_home, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :minute %>
    <%= form.number_field :minute, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/assists/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing assist</h1>

  <%= render "form", assist: @assist %>

  <%= link_to "Show this assist", @assist, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to assists", assists_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/assists/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Assists</h1>
    <%= link_to 'New assist', new_assist_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="assists" class="min-w-full">
    <%= render @assists %>
  </div>
</div>

app/views/assists/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New assist</h1>

  <%= render "form", assist: @assist %>

  <%= link_to 'Back to assists', assists_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/assists/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @assist %>

    <%= link_to 'Edit this assist', edit_assist_path(@assist), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this assist', assist_path(@assist), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to assists', assists_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>