config/routes.rb
Rails.application.routes.draw do

	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

	# Defines the root path route ("/")
	root 'dashboards#index'

	namespace :ceefax do
		resources :appearances
		resources :assists
		namespace :player_seasons do
			resources :attacking_stats
			resources :defensive_stats
			resources :discipline_stats
		end
		namespace :team_seasons do
			resources :goals_conceded_stats
			resources :goals_scored_stats
			resources :red_cards_stats
			resources :yellow_cards_stats
		end
		resources :cards
		resources :corners
		resources :countries
		resources :dashboards
		resources :fixtures
		resources :goals
		resources :head_to_heads
		resources :leagues
		resources :players
		resources :player_seasons
		resources :object_handling_failures
		resources :referees
		resources :referee_fixtures
		resources :seasons
		resources :season_game_weeks
		resources :teams
		resources :team_seasons

		root to: "dashboards#index"
	end

	resources :dashboards

	resources :countries do
		resources :leagues, only: [:index, :show, :update, :destroy] do
			resources :teams do
				resources :players, only: [:show, :update, :destroy]
			end
			resources :seasons, only: [:show, :update, :destroy] do
				member do
					get 'scorers_streaming'
					get 'assists_streaming'
					get 'bookings_streaming'
					get 'reds_streaming'
				end

				resources :teams, only: [:show] do
					resources :players, only: [:show, :update, :destroy]
				end

				resources :player_seasons
				resources :fixtures
				resources :assists
				resources :cards
				resources :goals
				resources :referees, only: [:index, :show, :update, :destroy]
			end
		end
	end

	resources :discipline_stats
	resources :defensive_stats
	resources :attacking_stats
	resources :corners
	resources :head_to_heads
	resources :fixtures, only: [:index]
	resources :referee_fixtures
	resources :referees
	resources :goals_conceded_stats
	resources :goals_scored_stats
	resources :leagues, only: [:index]
	resources :players, only: [:index, :show] do
		collection do
			get 'players_streaming'
		end
	end
	resources :team_seasons
	resources :teams, only: [:index, :show, :update, :destroy]

	get 'team_player_season_goals/:team_season_id', to: 'charts#team_player_season_goals', as: 'team_player_season_goals'
	get 'team_player_season_assists/:team_season_id', to: 'charts#team_player_season_assists', as: 'team_player_season_assists'
	get 'team_player_season_yellow_cards/:team_season_id', to: 'charts#team_player_season_yellow_cards', as: 'team_player_season_yellow_cards'
	get 'team_goals_radar/:current_team_season_id/:opponent_team_season_id', to: 'charts#team_goals_radar', as: 'team_goals_radar'
	get 'team_cards_line_chart/:current_team_season_id/:opponent_team_season_id', to: 'charts#team_cards_line_chart', as: 'team_cards_line_chart'
	get '/search', to: 'dashboards#search', as: 'search'

end

app/models/calculators/player_season/cards.rb
module Calculators
	module PlayerSeason
		class Cards
			def initialize(player_season)
				@player_season = player_season
			end

			def season_yellows_count
				yellow_cards.count
			end

			def season_home_yellows_count
				yellow_cards.where(is_home: true).count
			end

			def season_away_yellows_count
				yellow_cards.where(is_home: [false, nil]).count
			end

			def season_reds_count
				red_cards.count
			end

			def season_home_reds_count
				red_cards.where(is_home: true).count
			end

			def season_away_reds_count
				red_cards.where(is_home: [false, nil]).count
			end

			def first_half_home_yellow_cards_count
				first_half_yellow_cards.where(is_home: true).count
			end

			def first_half_away_yellow_cards_count
				first_half_yellow_cards.where(is_home: [false, nil]).count
			end

			def second_half_home_yellow_cards_count
				second_half_yellow_cards.where(is_home: true).count
			end

			def second_half_away_yellow_cards_count
				second_half_yellow_cards.where(is_home: [false, nil]).count
			end

			def first_half_home_red_cards_count
				first_half_red_cards.where(is_home: true).count
			end

			def first_half_away_red_cards_count
				first_half_red_cards.where(is_home: [false, nil]).count
			end

			def second_half_home_red_cards_count
				second_half_red_cards.where(is_home: true).count
			end

			def second_half_away_red_cards_count
				second_half_red_cards.where(is_home: [false, nil]).count
			end

			def average_minutes_per_home_yellow_card
				return ::PlayerSeason::ZERO if season_home_yellows_count.zero?

				player_season.total_home_minutes_played / season_home_yellows_count
			end

			def average_minutes_per_away_yellow_card
				return ::PlayerSeason::ZERO if season_away_yellows_count.zero?

				player_season.total_away_minutes_played / season_away_yellows_count
			end

			def average_minutes_per_home_red_card
				return ::PlayerSeason::ZERO if season_home_reds_count.zero?

				player_season.total_home_minutes_played / season_home_reds_count
			end

			def average_minutes_per_away_red_card
				return ::PlayerSeason::ZERO if season_away_reds_count.zero?

				player_season.total_away_minutes_played / season_away_reds_count
			end

			private

			attr_reader :player_season

			def yellow_cards
				player_season.cards.where(card_type: "yellow")
			end

			def first_half_yellow_cards
				yellow_cards.where(minute: 0..45)
			end

			def second_half_yellow_cards
				yellow_cards.where(minute: 46..100)
			end

			def red_cards
				player_season.cards.where(card_type: "red")
			end

			def first_half_red_cards
				red_cards.where(minute: 0..45)
			end

			def second_half_red_cards
				red_cards.where(minute: 46..100)
			end
		end
	end
end

app/models/card.rb
# == Schema Information
#
# Table name: cards
#
#  id                 :bigint           not null, primary key
#  card_type          :string
#  is_home            :boolean
#  minute             :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  appearance_id      :bigint           not null
#  first_card_id      :integer
#  fixture_id         :bigint           not null
#  player_season_id   :bigint           not null
#  referee_fixture_id :integer
#  team_season_id     :bigint           not null
#
# Indexes
#
#  index_cards_on_appearance_id     (appearance_id)
#  index_cards_on_card_type         (card_type)
#  index_cards_on_fixture_id        (fixture_id)
#  index_cards_on_player_season_id  (player_season_id)
#  index_cards_on_team_season_id    (team_season_id)
#
# Foreign Keys
#
#  fk_rails_...  (appearance_id => appearances.id) ON DELETE => cascade
#  fk_rails_...  (fixture_id => fixtures.id) ON DELETE => cascade
#  fk_rails_...  (player_season_id => player_seasons.id) ON DELETE => cascade
#  fk_rails_...  (team_season_id => team_seasons.id) ON DELETE => cascade
#
class Card < ApplicationRecord
	belongs_to :appearance
	belongs_to :player_season
	belongs_to :team_season, counter_cache: :yellow_cards_count
	belongs_to :fixture
	belongs_to :referee_fixture

	scope :home_cards, -> { where(is_home: true) }
	scope :away_cards, -> { where(is_home: nil) }
	scope :home_yellow_cards, -> { where(is_home: true, card_type: 'yellow') }
	scope :away_yellow_cards, -> { where(is_home: nil, card_type: 'yellow') }
	scope :home_red_cards, -> { where(is_home: true, card_type: 'red') }
	scope :away_red_cards, -> { where(is_home: nil, card_type: 'red') }
	scope :yellow_cards, -> { where(card_type: 'yellow') }
	scope :red_cards, -> { where(card_type: 'red') }
	scope :yellow_cards_for_team_season, ->(team_season_id) { where(card_type: 'yellow', team_season_id: team_season_id) }
	scope :red_cards_for_team_season, ->(team_season_id) { where(card_type: 'red', team_season_id: team_season_id) }
	scope :first_half_yellow_cards, ->(team_season_id) { yellow_cards.where('minute < ? AND team_season_id = ?', 46, team_season_id) }
	scope :second_half_yellow_cards, ->(team_season_id) { yellow_cards.where('minute > ? AND team_season_id = ?', 45, team_season_id) }
	scope :first_half_red_cards, ->(team_season_id) { red_cards.where('minute < ? AND team_season_id = ?', 46, team_season_id) }
	scope :second_half_red_cards, ->(team_season_id) { red_cards.where('minute > ? AND team_season_id = ?', 45, team_season_id) }
	scope :group_by_player_season, -> { group(:player_season_id) }
	scope :by_season, -> (season_id) {
		joins(team_season: :season)
			.where('seasons.id = ?', season_id)
			.includes(:player_season, :team_season)
			.group(:player_season_id)
			.order('COUNT(cards.id) desc')
			.count('cards.id')
	}

	def card_receiver_name
		player_season.return_name
	end

	def card_team_name
		team_season.name
	end

end

app/controllers/admin/cards_controller.rb
module Admin
  class CardsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[ show edit update destroy ]

  # GET /cards or /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1 or /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards or /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to card_url(@card), notice: "Card was successfully created." }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to card_url(@card), notice: "Card was successfully updated." }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1 or /cards/1.json
  def destroy
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url, notice: "Card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:minute, :card_type, :is_home, :first_card_id, :appearance_id, :player_season_id, :team_season_id, :fixture_id)
    end
end

app/controllers/ceefax/cards_controller.rb
module Ceefax
  class CardsController < Ceefax::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.erb
<div id="<%= dom_id card %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Minute:</strong>
    <%= card.minute %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Card type:</strong>
    <%= card.card_type %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Is home:</strong>
    <%= card.is_home %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">First card:</strong>
    <%= card.first_card_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Appearance:</strong>
    <%= card.appearance_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Player season:</strong>
    <%= card.player_season_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Team season:</strong>
    <%= card.team_season_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Fixture:</strong>
    <%= card.fixture_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this card", card, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this card', edit_card_path(card), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/cards/_form.html.erb
<%= form_with(model: card, class: "contents") do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :minute %>
    <%= form.number_field :minute, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :card_type %>
    <%= form.text_field :card_type, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :is_home %>
    <%= form.check_box :is_home, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :first_card_id %>
    <%= form.number_field :first_card_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :appearance_id %>
    <%= form.text_field :appearance_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :player_season_id %>
    <%= form.text_field :player_season_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :team_season_id %>
    <%= form.text_field :team_season_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :fixture_id %>
    <%= form.text_field :fixture_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing card</h1>

  <%= render "form", card: @card %>

  <%= link_to "Show this card", @card, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to cards", cards_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/cards/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Cards</h1>
    <%= link_to 'New card', new_card_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="cards" class="min-w-full">
    <%= render @cards %>
  </div>
</div>

app/views/cards/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New card</h1>

  <%= render "form", card: @card %>

  <%= link_to 'Back to cards', cards_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/cards/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @card %>

    <%= link_to 'Edit this card', edit_card_path(@card), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this card', card_path(@card), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to cards', cards_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>